name: "CI"
on: pull_request
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@v2
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        SKIP_FOLDERS: "foo,node_modules,vendor,tests,.github,wp-includes,wp-admin,wp-includes,wp-content/plugins,wp-content/uploads,wp-content/themes/twentytwenty,wp-content/themes/twentytwentyone,wp-content/themes/twentytwentytwo"
      with:
        args: "WordPress,WordPress-Core,WordPress-Docs"